# Generated by Django 2.2.7 on 2020-04-18 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(blank=True, max_length=200, unique=True)),
                ('live_stream', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 4, 18))),
                ('time', models.TimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('URL', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('camera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='console.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='access_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date(2020, 4, 18))),
                ('time', models.TimeField(auto_now_add=True)),
                ('accessed_camera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='console.Camera')),
            ],
        ),
    ]
