# Generated by Django 2.2.7 on 2020-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='duration',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
