# Generated by Django 2.2.7 on 2020-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20200418_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
