# Generated by Django 2.2.7 on 2020-04-18 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_auto_20200418_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_instance',
            name='accessed_camera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.Camera'),
        ),
    ]
