# Generated by Django 2.2.7 on 2020-04-19 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_auto_20200418_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_instance',
            name='accessed_footage_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='access_instance',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 19)),
        ),
        migrations.AlterField(
            model_name='footage',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 19)),
        ),
    ]
